import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { FaUser } from 'react-icons/fa'

import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>nearmaick.dev.br | início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.home}>
        <div className={styles.image}>
          <img src="https://github.com/nearmaick.png" alt="Maick Souza Foto" />
        </div>

        <div className={styles.content}>
          <h3>Olá, sou Maick Souza</h3>
          <span>JavaScript FullStack Developer</span>
          <p>Uma pessoa de hoje que sempre deseja ser melhor amanhã!</p>
          <Link href="/">
            <a className={styles.linkButton}>
              <div>
                Sobre mim
                <FaUser />
              </div>
            </a>
          </Link>
        </div>
      </section>
    </>
  )
}

export default Home
